apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: {{ include "youcanbenefit-chart.frontend.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "youcanbenefit-chart.frontend.name" . }}
    helm.sh/chart: {{ include "youcanbenefit-chart.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  replicas: {{ .Values.frontend.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "youcanbenefit-chart.frontend.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "youcanbenefit-chart.frontend.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      containers:
        - name: {{ include "youcanbenefit-chart.frontend.fullname" . }}
          image: "{{ .Values.frontend.image.repository }}:{{ .Values.frontend.image.tag }}"
          imagePullPolicy: {{ .Values.frontend.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          env:
            - name: API_SERVICE
              value: {{ include "youcanbenefit-chart.backend.fullname" . }}
            - name: API_PORT
              value: {{ .Values.backend.service.port | quote}}
            - name: ADMIN_USERNAME
              value: {{ .Values.admin.username }}
            - name: ADMIN_PASSWORD
              value: {{ .Values.admin.password }}
          resources:
{{ toYaml .Values.frontend.resources | indent 12 }}

