apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: {{ include "youcanbenefit-chart.frontend.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "youcanbenefit-chart.frontend.name" . }}
    helm.sh/chart: {{ include "youcanbenefit-chart.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  replicas: {{ .Values.frontend.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "youcanbenefit-chart.frontend.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "youcanbenefit-chart.frontend.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      containers:
        - name: {{ include "youcanbenefit-chart.frontend.fullname" . }}
          image: "{{ .Values.frontend.image.repository }}:{{ .Values.frontend.image.tag }}"
          imagePullPolicy: {{ .Values.frontend.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          resources:
{{ toYaml .Values.frontend.resources | indent 12 }}
