version: '3.2'
services:

  caddy:
    image: abiosoft/caddy:0.11.2
    environment:
     - DOMAIN_NAME=example.com
     - EMAIL_FOR_DOMAIN=example@gmail.com
     - ACME_AGREE=true
     - WEB_SERVICE=web
    ulimits:
      nofile:
        soft: 8196
        hard: 8196
    volumes:
     - type: bind
       source: ./Caddyfile
       target: /etc/Caddyfile
     - type: bind
       source: ${HOME}/.caddy
       target: /root/.caddy
    ports:
      - 80:80
      - 443:443

  web:
    image: cityofedmonton/youcanbenefit-web:latest
    environment:
      - ADMIN_USERNAME=user
      - ADMIN_PASSWORD=password
      - API_SERVICE=api
      - API_PORT=3000
    ulimits:
      nofile:
        soft: 8196
        hard: 8196
    restart: always

  api:
    image: cityofedmonton/youcanbenefit-api:latest
    environment:
      - ELASTICSEARCH_URL=elasticsearch:9200
    restart: always

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.4.2
    environment:
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      nofile:
        soft: 65536
        hard: 65536
      memlock:
        soft: -1
        hard: -1
    volumes:
      - esdata:/usr/share/elasticsearch/data
    restart: always

volumes:
  esdata:
    driver: local